import { Helmet } from 'react-helmet';

const SEO = ({ pageTitle }) => (
  <Helmet>
    <title>{pageTitle && `${pageTitle} - E-commerce React Template`}</title>
    <meta httpEquiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="Generated by create react app" />
    <meta name="robots" content="noindex, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="/favicon.png" />
  </Helmet>
);

export default SEO;
